spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE